apiVersion: apps/v1
kind: Deployment
metadata:
  name: tirea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tirea
  template:
    metadata:
      labels:
        app: tirea
    spec:
      containers:
      - image: okteto.dev/tirea:latest
        name: tirea
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "0252c5bd-644a-4d02-a5c2-4bacf0a1f5d8"
        - name: Vless_Path
          value: "/sheri"
        - name: Vmess_UUID
          value: "0252c5bd-644a-4d02-a5c2-4bacf0a1f5d8"
        - name: Vmess_Path
          value: "/shoue"
        - name: Share_Path
          value: "/liuet"
